
development:
  adapter: postgresql
  encoding: unicode
  database: marking_generator_development
  pool: 5
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

 
test:
  adapter: postgresql
  encoding: unicode
  database: marking_generator_test
  pool: 5
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: marking_generator_production
  pool: 5
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>